"""PPO defaults for single-GPU training."""

config_ppo = {
    "max_iters": 600,
    "lr": 5e-4,
    "gamma": 0.99,
    "lambda_": 0.95,
    "train_batch_size_per_learner": 4096,
    "minibatch_size": 512,
    "num_epochs": 30,
    "entropy_coeff": 0.003,
    "vf_loss_coeff": 1.0,
    "clip_param": 0.2,
    "num_learners": 1,
    "num_gpus_per_learner": 1,
    "num_cpus_per_learner": 1,
    "num_env_runners": 6,
    "num_envs_per_env_runner": 3,
    "num_cpus_per_env_runner": 2,
    "num_cpus_for_main_process": 2,
    "sample_timeout_s": 600,
    "rollout_fragment_length": "auto",
    "kl_coeff": 0.2,
    "kl_target": 0.01,
    # PBT hooks reuse CPU defaults
    "pbt_lr_choices": [1e-4, 3e-4, 5e-4],
    "pbt_num_epochs_range": (15, 40),
    "pbt_minibatch_choices": [256, 384, 512],
    "pbt_train_batch_size_choices": [2048, 4096, 6144],
    "perturbation_interval": 6,
    "resample_probability": 0.25,
    "quantile_fraction": 0.25,
    "pbt_num_samples": 6,
}
