"""Base environment configuration for PredPreyGrass env129.

Values are copied from the legacy `prey_test_config` so scripts can import a
single canonical source and layer overrides on top (train/eval, smoke, etc.).
"""

config_env_base = {
    # === World settings ===
    "enable_continuous_space": True,
    "world_width": 600,
    "world_height": 600,
    "agent_radius": 4,
    # === Rewards ===
    "reward_predator_catch_prey": 6.0,
    "reward_prey_eat_grass": 1.2,
    "reward_predator_step": -0.015,
    "reward_prey_step":  -0.01,
    "penalty_prey_caught": -6.0,
    "reproduction_reward_predator": 3.5,
    "reproduction_reward_prey": 3.0,
    "survival_bonus_predator": 0.4,
    "survival_bonus_prey": 0.2,
    "allow_empty_predator_population": False,
    # === Population settings ===
    # Initial active counts per species (will be evenly split across populations).
    "n_initial_active_predator": 30,  # 5 populations * 6 each
    "n_initial_active_prey": 100,     # 5 populations * 20 each
    "n_possible_predators": 20000,
    "n_possible_prey": 20000,
    "n_populations": 5,
    # Optional labels for GUI/debug; keys should match "{species}_{pop_id}".
    "population_display_info": {
        "predator_0": "pred-pop0",
        "predator_1": "pred-pop1",
        "predator_2": "pred-pop2",
        "predator_3": "pred-pop3",
        "predator_4": "pred-pop4",
        "prey_0": "prey-pop0",
        "prey_1": "prey-pop1",
        "prey_2": "prey-pop2",
        "prey_3": "prey-pop3",
        "prey_4": "prey-pop4",
    },
    # === Grass system ===
    "initial_num_grass": 150,
    "initial_energy_grass": 1,
    "energy_gain_per_step_grass": 0.01,
    "grass_energy_decay_constant": 0.0,
    "enable_grass_reproduction": False,
    "grass_reproduction_age": 80,
    "grass_reproduction_energy_threshold": 10.0,
    "grass_reproduction_cooldown": 60,
    "grass_perception_radius": 400.0,
    "grass_reference_neighbors": 0.1,
    "grass_density_cache_interval": 10,
    "grass_reproduction_range": 400.0,
    "grass_reproduction_cost": 2.0,
    "grass_offspring_energy": 10.0,
    "grass_spawn_max_attempts": 2,
    "grass_respawn_delay": 150,
    "fixed_grass_mode": True,
    # === Energy system ===
    "initial_energy_predator": 2.0,
    "energy_loss_per_step_predator": 0.012,
    "predator_creation_energy_threshold": 5.5,
    "initial_energy_prey": 1.0,
    "energy_loss_per_step_prey": 0.008,
    "prey_creation_energy_threshold": 3.0,
    "enable_soft_energy_limit": False,
    "energy_saturation_predator": 2.0,
    "energy_saturation_prey": 1.8,
    "enable_max_energy": False,
    "max_energy_predator": 50.0,
    "max_energy_prey": 20.0,
    "energy_transfer_efficiency": 0.9,
    "energy_transfer_efficiency_predator": 0.7,
    "energy_transfer_efficiency_prey": 0.9,
    "metabolism_rate": 0.0,
    "base_metabolism": 0.0,
    "base_metabolism_predator": 0.00,
    "base_metabolism_prey": 0.00,
    "movement_cost_factor": 0.0,
    "movement_cost_factor_predator": 0.00,
    "movement_cost_factor_prey": 0.00,
    "thrust_cost_factor": 0.000,
    "thrust_cost_factor_predator": 0.00,
    "thrust_cost_factor_prey": 0.00,
    "thrust_penalty_scale_predator": 0.0,
    "thrust_penalty_scale_prey": 0.0,
    "turn_penalty_factor": 0.00,
    "turn_penalty_factor_predator": 0.00,
    "turn_penalty_factor_prey": 0.00,
    # === Reproduction system ===
    "enable_paired_reproduction": True,
    "reproduction_mode": "ratio",
    "reproduction_energy_ratio": 0.5,
    "reproduction_energy_ratio_predator": 0.3,
    "reproduction_energy_ratio_prey": 0.5,
    "min_reproduction_age": 50,
    "min_reproduction_age_predator": 50,
    "min_reproduction_age_prey": 10,
    "max_reproduction_age": 50000,
    "reproduction_cooldown": 10,
    "reproduction_cooldown_predator": 50,
    "reproduction_cooldown_prey": 10,
    "mating_distance": 100.0,
    "max_population_size": 20000,
    "max_population_size_predator": 20000,
    "max_population_size_prey": 20000,
    # === Physics ===
    "n_sensors": 20,
    "sensor_range": 100.0,
    "sensor_range_predator": 300.0,
    "sensor_range_prey": 300.0,
    "thrust_scale_predator": 0.0,
    "thrust_scale_prey": 0.0,
    "soft_speed_limit_predator": None,
    "soft_speed_limit_prey": None,
    "drag_coefficient": 0.0,
    "use_direct_velocity_control": True,
    "direct_velocity_speed_predator": 300.0,
    "direct_velocity_speed_prey": 300.0,
    "direct_velocity_accel_scale_predator": 60.0,
    "direct_velocity_accel_scale_prey": 40.0,
    # === Hunger system ===
    "enable_hunger": True,
    "max_steps_without_food_predator": 200,
    "max_steps_without_food_prey": 400,
    "hunger_damage": 0.00005,
    # === Collisions ===
    "enable_agent_collision": False,
    "collision_damage": 0.3,
    "wall_collision_damage": 0.5,
    # === Simulation ===
    "max_steps": 500,
    "verbose_spawning": True,
    "verbose_engagement": True,
    "verbose_movement": True,
}
