"""Tiny PPO config for smoke tests (fast & cheap)."""

config_ppo = {
    "max_iters": 5,
    "lr": 3e-4,
    "gamma": 0.99,
    "lambda_": 0.95,
    "train_batch_size_per_learner": 512,
    "minibatch_size": 64,
    "num_epochs": 2,
    "entropy_coeff": 0.0,
    "vf_loss_coeff": 1.0,
    "clip_param": 0.3,
    "num_learners": 1,
    "num_gpus_per_learner": 0,
    "num_cpus_per_learner": 1,
    "num_env_runners": 1,
    "num_envs_per_env_runner": 1,
    "num_cpus_per_env_runner": 1,
    "num_cpus_for_main_process": 1,
    "sample_timeout_s": 120,
    "rollout_fragment_length": 64,
    "kl_coeff": 0.2,
    "kl_target": 0.01,
    "pbt_lr_choices": [1e-4, 3e-4],
    "pbt_num_epochs_range": (1, 3),
    "pbt_minibatch_choices": [32, 64],
    "pbt_train_batch_size_choices": [256, 512],
    "perturbation_interval": 2,
    "resample_probability": 0.5,
    "quantile_fraction": 0.5,
    "pbt_num_samples": 2,
}
